# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

on_execution_done <- function(id, cv) {
    invisible(.Call(`_vrpc_on_execution_done`, id, cv))
}

start_vrpc_agent <- function(broker = "mqtt://vrpc.io:1883",
                             domain = "public.vrpc",
                             agent = NULL,
                             username = NULL,
                             password = NULL,
                             token = NULL,
                             functions = NULL,
                             packages = NULL) {
    all_functions <- as.vector(lsf.str(envir = .GlobalEnv))
    if (!is.null(functions)) {
        all_functions <- functions
    }
    if (!is.null(packages)) {
        tmp <- sapply(
            packages,
            function(x) paste0(paste0(x, "$"), lsf.str(paste0("package:", x)))
        )
        for (x in tmp) {
            all_functions <- c(all_functions, x)
        }
    }
    invisible(.Call(`_vrpc_start_vrpc_agent`, list(
        broker = broker,
        domain = domain,
        agent = agent,
        username = username,
        password = password,
        token = token,
        functions = all_functions
    )))
}
