name: CI
on: [push, workflow_dispatch]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      working-directory: test
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: test.sh
